Repository kakao-tech-campus-3rd-step3/Team18_FE, pull requests merged in 2025-09, with the labels that each got.

#3 chore: 기본 설정 추가
  .nvmrc
  package-lock.json
  package.json
Labels: ⚙️ chore

#5 [FIX]eslint 관련 충돌 해결#4
  package-lock.json
  package.json
  yarn.lock
Labels: 🐛 bug, ⚙️ chore

#8 [FEAT]디자인토큰 생성#6
  src/App.tsx
  src/styles/theme.ts
  src/styles/tokens/colors.ts
  src/styles/tokens/tokens.ts
  src/types/emotion.d.ts
Labels: ✨ Feature, 🌈 frontend

#13 [FEAT]공통 컴포넌트#10
  src/App.tsx
  src/components/Button.tsx
  src/components/Navbar.tsx
  src/styles/theme.ts
  src/styles/tokens/colors.ts
  src/styles/tokens/tokens.ts
  src/types/emotion.d.ts
Labels: ✨ Feature, 🌈 frontend

#12 [FEAT] 메인페이지 UI 구현(#7)
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/main.tsx
  src/mocks/client.ts
  src/mocks/handlers.ts
  src/pages/Routes.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/api/club.ts
  src/pages/main/components/BannerSection/BannerText.tsx
  src/pages/main/components/BannerSection/BannerWrapper.tsx
  src/pages/main/components/BannerSection/ClubSearchInput.tsx
  src/pages/main/components/BannerSection/index.tsx
  src/pages/main/components/ClubCategorySection/CategoryTab.tsx
  src/pages/main/components/ClubCategorySection/index.tsx
  src/pages/main/components/ClubListSection/ClubGrid.tsx
  src/pages/main/components/ClubListSection/ClubInfo.tsx
  src/pages/main/components/ClubListSection/ClubItem.tsx
  src/pages/main/components/ClubListSection/ClubListContainer.tsx
  src/pages/main/components/ClubListSection/index.tsx
  src/pages/main/constant/clubCategory.ts
  src/pages/main/domain/club.ts
  src/pages/main/hook/useClub.ts
  src/pages/main/type/club.ts
  src/types/emotion.d.ts
Labels: 🎨 UI

#17 [REFACTOR] 공통 컴포넌트 수정 (#16)
  src/App.tsx
  src/components/Button.tsx
  src/components/Navbar.tsx
  src/constants/navigation.ts
  src/shared/components/Button/index.tsx
  src/shared/components/Navigation/NavigationContainer.tsx
  src/shared/components/Navigation/NavigationItem.tsx
  src/shared/components/Navigation/index.tsx
  src/types/navigation.ts
Labels: 🛠️ Refactor, ✨ Feature

#40 [FEAT] 간단한 섹션타이틀 컴포넌트 추가
  src/shared/components/SectionTitle/index.tsx
Labels: ✨ Feature

#59 [REFACTOR]동아리 검색 개선 #43
  public/assets/noSearchResults.svg
  src/pages/user/Main/components/ClubCategorySection/index.styled.ts
  src/pages/user/Main/components/ClubCategorySection/index.tsx
  src/pages/user/Main/components/ClubListSection/Club.styled.ts
  src/pages/user/Main/components/ClubListSection/index.tsx
  src/pages/user/Main/utils/searchClubs.ts
Labels: 🛠️ Refactor

#65 [REFACTOR] 별점 렌더링 성능 개선 (#64)
  src/pages/admin/ApplicationDetail/components/ApplicantProfileSection/ApplicantStarRating.tsx
Labels: 🛠️ Refactor

#67 [CHORE] Router path 수정 #66
  .github/workflows/ci.yml
  src/constants/navigation.ts
  src/constants/routerPath.ts
  src/mocks/client.ts
  src/mocks/handler/applicant.ts
  src/mocks/handler/club.ts
  src/pages/admin/ApplicationDetail/api/detailApplication.ts
  src/pages/admin/Dashboard/api/applicant.ts
  src/pages/user/Main/api/club.ts
Labels: ⚙️ chore

#82 [REFACTOR] 동아리 카테고리 queryParam 인코딩 에러 해결
  src/mocks/handler/club.ts
  src/mocks/repositories/club.ts
  src/pages/user/Main/Page.tsx
  src/pages/user/Main/api/club.ts
  src/pages/user/Main/components/ClubCategorySection/index.tsx
  src/pages/user/Main/components/ClubListSection/index.tsx
  src/pages/user/Main/constant/clubCategory.ts
  src/pages/user/Main/hook/useClub.ts
  src/pages/user/Main/utils/formatting.ts
Labels: 🐛 bug

#95 [REFACTOR] 상세페이지들의 route & API 구조 (#87)
  src/constants/routerPath.ts
  src/pages/admin/ClubDetailEdit/components/ClubDescriptionEditSection/index.tsx
  src/pages/admin/ClubDetailEdit/components/ClubInfoSidebarEditSection/index.tsx
  src/pages/admin/ClubDetailEdit/components/mock.ts
  src/pages/user/ClubDetail/components/ClubDescriptionSection/index.tsx
  src/pages/user/ClubDetail/components/ClubInfoSidebarSection/index.tsx
  src/pages/user/ClubDetail/components/mock.ts
Labels: 🛠️ Refactor

#106 [REFACTOR] MSW applicantHandlers 코딩 스타일 일관성 개선 (#105)
  src/mocks/handler/applicant.ts
Labels: 🛠️ Refactor
