Repository kakao-tech-campus-3rd-step3/Team18_FE, pull requests merged in 2025-10, with the labels that each got.

#123 [STYLE] 동아리 상세페이지& 지원서 작성 페이지 UI 개선 (#120)
  src/pages/user/Apply/Page.tsx
  src/pages/user/Apply/components/ApplicationForm/index.styled.ts
  src/pages/user/Apply/components/ApplicationForm/index.tsx
  src/pages/user/Apply/components/ClubDescriptionSection/index.tsx
  src/pages/user/ClubDetail/components/ClubDescriptionSection/index.tsx
  src/pages/user/ClubDetail/components/ClubInfoSidebarSection/index.tsx
  src/shared/components/ClubDetailLayout/ClubHeaderSection.tsx
  src/shared/components/ClubDetailLayout/index.styled.ts
Labels: 🎨 UI

#125 [REFACTOR] Route 상수 계층 구조 적용 (#109)
  src/constants/routerPath.ts
  src/pages/Routes.tsx
Labels: 🛠️ Refactor

#122 [REFACTOR] questionType의 SSOT 원칙 적용 (#101)
  src/pages/user/Apply/components/ApplicationForm/index.tsx
  src/pages/user/Apply/constant/questionType.ts
  src/pages/user/Apply/type/apply.ts
Labels: 🛠️ Refactor

#127 [FEAT] 지원서 댓글 CRUD 기능 구현 (#112)
  src/constants/navigation.ts
  src/mocks/handler/applicant.ts
  src/mocks/repositories/applicant.ts
  src/pages/admin/ApplicationDetail/api/comments.ts
  src/pages/admin/ApplicationDetail/components/CommentSection/CommentForm.tsx
  src/pages/admin/ApplicationDetail/components/CommentSection/CommentItem.tsx
  src/pages/admin/ApplicationDetail/components/CommentSection/CommentList.tsx
  src/pages/admin/ApplicationDetail/components/CommentSection/index.tsx
  src/pages/admin/ApplicationDetail/hooks/useComments.ts
  src/pages/admin/ApplicationDetail/types/comments.ts
  src/shared/components/Form/TextAreaField/UnderlineTextareaField.tsx
Labels: ✨ Feature

#129 [REFACTOR] 시간 선택 컴포넌트 관심사 분리 #126
  src/pages/user/Apply/components/ApplicationForm/InterviewScheduleSelector.tsx
  src/pages/user/Apply/components/ApplicationForm/Schedule.tsx
  src/pages/user/Apply/components/ApplicationForm/index.tsx
  src/pages/user/Apply/hook/useDragSelection.ts
  src/pages/user/Apply/hook/useUpdateFormData.ts
  src/pages/user/Apply/utils/time.ts
Labels: 🛠️ Refactor
